// WARNING: Generated by `build/main.rs`, do NOT change manually!

pub mod instruction;
pub mod enumeration;

pub const SPIRV_MAGIC: usize = 0x07230203;
pub const SPIRV_VERSION: (usize, usize) = (1, 1);
pub const SPIRV_REVISION: usize = 2;
